version: '3'
services:
  prime-number-server:
    build:
      context: ../prime-number-app
      dockerfile: prime-number-server/infrastructure/docker/Dockerfile
      args:
        jarFile: ./prime-number-server/build/libs/*.jar
    ports:
      - 9090:9090
    entrypoint: [
      "java",
      "-Dcom.sun.management.jmxremote",
      "-Dcom.sun.management.jmxremote.local.only=false",
      "-Dcom.sun.management.jmxremote.ssl=false",
      "-Dcom.sun.management.jmxremote.authenticate=false",
      "-Dcom.sun.management.jmxremote.port=9999",
      "-Dcom.sun.management.jmxremote.rmi.port=9999",
      "-Djava.rmi.server.hostname=localhost",
      "-Djava.security.egd=file:/dev/./urandom",
      "-jar",
      "/app.jar"
    ]

  prime-number-proxy-service:
    build:
      context: ../prime-number-app
      dockerfile: prime-number-proxy-service/infrastructure/docker/Dockerfile
      args:
        jarFile: ./prime-number-proxy-service/build/libs/*.jar
    ports:
      - 8080:8080
    environment:
      - GRPC_SERVER_HOST=prime-number-server
      - GRPC_SERVER_PORT=9090
    entrypoint: [
        "java",
        "-Dcom.sun.management.jmxremote",
        "-Dcom.sun.management.jmxremote.local.only=false",
        "-Dcom.sun.management.jmxremote.ssl=false",
        "-Dcom.sun.management.jmxremote.authenticate=false",
        "-Dcom.sun.management.jmxremote.port=9999",
        "-Dcom.sun.management.jmxremote.rmi.port=9999",
        "-Djava.rmi.server.hostname=localhost",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/app.jar"
    ]
    depends_on:
      prime-number-server:
        condition: service_started
